## ConfigMap
apiVersion: v1
kind: ConfigMap
metadata: 
  name: catalogue
  namespace: safety
data: 
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
## Deplyments
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: catalogue
  namespace: safety
# these are deployment labels
  labels:
    project: safety
    component: catalogue
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: safety
      component: catalogue
      tier: backend
    # pod definitdion
  template: 
    metadata:
      labels:
        project: safety
        component: catalogue
        tier: backend
    spec:
      containers:
      - name: catalogue
        image: hanvihanshith/catalogue:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: catalogue
        ports: 
        - name: liveness-port
          containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: 500Mi
          limits:
            cpu: "100m"
            memory: 500Mi
        readinessProbe:
          httpGet:
            path: /health 
            port: 8080  
          failureThreshold: 1
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /health 
            port: 8080  
          failureThreshold: 1
          periodSeconds: 20
---
### Service creation
apiVersion: v1 
kind: Service
metadata: 
  name: catalogue
  namespace: safety
spec:
  selector:
    project: safety
    component: catalogue
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 ## services port
      targetPort: 8080 ## container port
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue
  namespace: safety
  labels:
    project: safety
    component: catalogue
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 6
